# Stage 1: Build the Vite app
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
COPY . .
RUN npm install
RUN npm run build

# Stage 2: Serve the Vite app using a simple static file server (e.g., serve)
FROM node:18-alpine AS prod
WORKDIR /app
COPY --from=build /app/dist /app

RUN npm install -g serve

CMD ["serve", "-s", "/app", "-l", "3000"]
